kbase/narrative_method_specs

- methods/normalize_abundance_profile/display.yaml
- methods/normalize_abundance_profile/spec.json
- methods/pcoa_from_abundance_profile/display.yaml
- methods/pcoa_from_abundance_profile/spec.json
- methods/retrieve_functional_abundance_profile/display.yaml
- methods/retrieve_functional_abundance_profile/spec.json
- methods/retrieve_taxonomic_abundance_profile/display.yaml
- methods/retrieve_taxonomic_abundance_profile/spec.json
- methods/view_abundance_profile_boxplots/display.yaml
- methods/view_abundance_profile_boxplots/spec.json
- methods/view_abundance_profile_heatmap/display.yaml
- methods/view_abundance_profile_heatmap/spec.json
- methods/view_abundance_profile_pcoa/display.yaml
- methods/view_abundance_profile_pcoa/spec.json
- methods/view_abundance_profile_rank_plot/display.yaml
- methods/view_abundance_profile_rank_plot/spec.json
- methods/view_abundance_profile_values/display.yaml
- methods/view_abundance_profile_values/spec.json
> Method name changes requested by documentation team

- methods/import_contigset_fasta_file/display.yaml
- methods/import_contigset_fasta_file/spec.json
- methods/import_contigset_fasta_ftp/display.yaml
- methods/import_contigset_fasta_ftp/spec.json
> 'fastaReferenceOnly' parameter was added into fasta-to-contigset

- methods/insert_genome_into_species_tree_generic/display.yaml
- methods/insert_genome_into_species_tree_generic/spec.json
- methods/insert_set_of_genomes_into_species_tree_generic/display.yaml
Tested and worked find on https://narrative-sandbox.kbase.us/narrative/ws.3581.obj.1
> Fix for the JIRA ticket https://atlassian.kbase.us/browse/NAR-490 . tested on narrative-sandbox

- methods/import_contigset_fasta_file/display.yaml
- methods/import_contigset_fasta_ftp/display.yaml
- methods/import_fbamodel_csv_file/display.yaml
- methods/import_fbamodel_sbml_file/display.yaml
- methods/import_media_csv_file/display.yaml
- methods/import_media_csv_file/spec.json
- methods/import_phenotypeset_csv_file/display.yaml
- methods/import_phenotypeset_csv_file/spec.json
- methods/import_reads_fasta_file/display.yaml
- methods/import_reads_pe_fastq_file/display.yaml
- methods/import_reads_se_fastq_file/display.yaml
- types/KBaseBiochem.Media/display.yaml
- types/KBaseBiochem.Media/spec.json
- types/KBasePhenotypes.PhenotypeSet/spec.json
"Workspace" keyword was substituted by "Narrative" in all import method specs.
> Methods for CSV-to-Media and CSV-to-PhenotypeSet importers were added.

- methods/annotate_contigset/display.yaml
- methods/insert_set_of_genomes_into_species_tree_generic/display.yaml
addresses https://atlassian.kbase.us/browse/NAR-654
> Minor doc update

- methods/import_genome_gbk_file/display.yaml
- methods/import_genome_gbk_ftp/display.yaml
> added 2G limit message for Genbank upload (untested)

- methods/build_genome_set_from_tree_generic/display.yaml
in response to a bug that was introduced in https://github.com/kbase/narrative_method_specs/pull/160
> fixed bug in yaml

- methods/import_transcript_file/display.yaml
https://atlassian.kbase.us/browse/KBASE-1565
> Fix for wrong descriptions in transcript uploader.

- methods/insert_genomeset_into_species_tree_generic/spec.json
for "Insert GenomeSet into Species Tree".
> Limitation for number of neighbors in spec.json

- .gitmodules
- .travis.yml
- Makefile
- README.md
- methods/compare_two_proteomes_generic/display.yaml
- methods/view_abundance_profile_data/display.yaml
- methods/view_abundance_profile_values/display.yaml
This is a small pull request, but it does a couple important things.
First, this request marks a switch from using the 'dev' branch for incoming pull requests to the 'develop' branch so that we use the same emerging conventions as other KBase projects.  Please make pull requests against 'develop' from now on.
Second, this repo is now configured to run automated tests with Travis-CI (https://travis-ci.org/kbase/narrative_method_specs).  The tests use tooling from the narrative_method_store to validate most aspects of method/app/type specifications (e.g. required fields, proper structure, proper JSON/Yaml syntax) against a running narrative_method_store server (https://ci.kbase.us/services/narrative_method_store/rpc).  These tests will automatically run on each pull request to the …
> Moving default branch to develop; Added automated testing with travis-ci

- methods/heatmap_from_abundance_profile/display.yaml
- methods/normalize_abundance_profile/display.yaml
- methods/pcoa_from_abundance_profile/display.yaml
- methods/retrieve_functional_abundance_profile/display.yaml
- methods/retrieve_taxonomic_abundance_profile/display.yaml
- methods/view_abundance_profile_boxplots/display.yaml
This is for JIRA ticket: https://atlassian.kbase.us/browse/KBASE-2066
> changes to method field names for clarification and consistency

- methods/import_fbamodel_csv_file/display.yaml
(By the way, why is this repo called import_fbamodel_csv_file when it actually imports TSV files, not csv? Does it accept csv files also?)
> Added long-hints

- methods/expression_toolkit_filter_expression/spec.json
This PR also adds basic parameter validation for this method that was missing.
> Hotfix - reactivate method to find differentially expressed genes

- methods/view_abundance_profile_rank_plot/spec.json
> Hiding (inactivating) unsupported Communities methods

- apps/communities_build_functional_profile/spec.json
> Hiding (inactivating) unsupported Communities app

- methods/metagenome_annotation_to_models/spec.json
> Hiding "Build Models from Metagenome" method

- methods/metagenome_list/spec.json
> Hiding "Create Metagenome Set" method

- methods/retrieve_functional_abundance_profile/spec.json
> Hide "Generate Functional Abundance Data" method

- methods/heatmap_from_abundance_profile/spec.json
> Hide "Generate Heatmap from Abundance Data" method

- methods/pcoa_from_abundance_profile/spec.json
> Hide "Generate PCoA from Abundance Data" method

- methods/retrieve_taxonomic_abundance_profile/spec.json
> Hide "Generate Taxonomic Abundance Data" method

- methods/view_abundance_profile_boxplots/spec.json
> Hiding "Generate Boxplots for Abundance Data" method

- methods/view_abundance_profile_heatmap/spec.json
> Hide "View Abundance Data Heatmap" method

- methods/view_abundance_profile_values/spec.json
> Hide "View Abundance Data Table" method

- methods/view_abundance_profile_data/spec.json
> Hide "View Abundance Data" method

- apps/community_fba_modeling/spec.json
As requested by Chris H (see https://atlassian.kbase.us/browse/KBASE-2977)
> Hide "Reconstruct Community Metabolic Model" app

- methods/view_abundance_profile_pcoa/spec.json
> Hide method "View Abundance Data PCoA"

- methods/normalize_abundance_profile/spec.json
(Thought I already did this one?)
> Hide "Normalize Abundance Data" method

- methods/import_contigset_fasta_file/display.yaml
> Added long description

- methods/import_expression_tsv_file/display.yaml
for Upload an expression data matrix from a TSV file.
> Improved description

- methods/import_fbamodel_csv_file/display.yaml
Right now, just suggests you look at http://kbase.us/data-upload-download-guide/fba-model/ (which actually doesn't yet include information about how to format an FBA model in CSV format, but hopefully it will soon).
> Added description

- methods/import_fbamodel_sbml_file/display.yaml
Provide link to FBA model page of Upload-Download guide
> Added description field

- apps/build_plant_metabolic_model/display.yaml
- methods/annotate_plant_transcripts/display.yaml
Again, let me check with plant team before merging
> Replacing transcript with coding sequence in plant metabolic modeling

- methods/edit_media/display.yaml
- methods/edit_media/spec.json
- methods/edit_model/display.yaml
- methods/edit_model/spec.json
output widget isn't used, but gonna leave it there assuming it does no harm.
> add editor methods

- methods/sdk_request_release/display.yaml
> Fixed typo in method name

- apps/build_fba_model/spec.json
- apps/build_plant_metabolic_model/spec.json
- apps/build_species_tree/spec.json
- apps/fba_model_translation/spec.json
- apps/genome_assembly/spec.json
- apps/genome_comparison/spec.json
- methods/edit_media/spec.json
- methods/edit_model/spec.json
This removes the old legacy apps and methods.  This should be consistent with prod.
> remove legacy apps and methods

- types/KBaseBiochem.Media/spec.json
This must have gotten skipped during the December deploy
> Fix Media uploaders

- types/KBaseAssembly.PairedEndLibrary/display.yaml
- types/KBaseAssembly.PairedEndLibrary/spec.json
- types/KBaseAssembly.SingleEndLibrary/display.yaml
- types/KBaseAssembly.SingleEndLibrary/spec.json
- types/KBaseFile.PairedEndLibrary/display.yaml
- types/KBaseFile.PairedEndLibrary/spec.json
- types/KBaseFile.SingleEndLibrary/display.yaml
- types/KBaseFile.SingleEndLibrary/spec.json
- types/KBaseOntology.OntologyDictionary/display.yaml
- types/KBaseOntology.OntologyDictionary/spec.json
- types/KBaseOntology.OntologyTranslation/display.yaml
- types/KBaseOntology.OntologyTranslation/spec.json
- types/KBaseRNASeq.RNASeqAlignment/display.yaml
- types/KBaseRNASeq.RNASeqAlignment/spec.json
- types/KBaseRNASeq.RNASeqAlignmentSet/display.yaml
- types/KBaseRNASeq.RNASeqAlignmentSet/spec.json
- types/KBaseRNASeq.RNASeqDifferentialExpression/display.yaml
- types/KBaseRNASeq.RNASeqDifferentialExpression/spec.json
- types/KBaseRNASeq.RNASeqExpression/display.yaml
- types/KBaseRNASeq.RNASeqExpression/spec.json
- types/KBaseRNASeq.RNASeqExpressionSet/display.yaml
- types/KBaseRNASeq.RNASeqExpressionSet/spec.json
- types/KBaseRNASeq.RNASeqSampleSet/display.yaml
- types/KBaseRNASeq.RNASeqSampleSet/spec.json
This pulls in a bunch of missing types from CI.
> Added various types to get viewers, uploaders, and downloaders

- types/KBaseBiochem.Media/spec.json
I am adding @scanon  and @msneddon as reviewers
> removing FBAFileUtil method names for media upload

- types/KBaseBiochem.CompoundSet/display.yaml
- types/KBaseBiochem.CompoundSet/spec.json
Downloaders for Compound Set. Tested in CI
> Add downloaders for CompoundSet data type

- types/KBaseCollections.FeatureSet/spec.json
Have tested this on CI already
> Add FeatureSet TSV downloader

- methods/test_method_10/display.yaml
- methods/test_method_10/spec.json
Have one for each initial data type
> Add new test data for dynamic_dropdown

- types/KBaseFile.PairedEndLibrary/spec.json
- types/KBaseFile.SingleEndLibrary/spec.json
- types/KBaseGenomeAnnotations.Assembly/spec.json
- types/KBaseGenomes.Genome/spec.json
- types/KBaseRNASeq.RNASeqAlignment/spec.json
@briehl Could you take a look?
> add staging exporter

- types/KBaseFile.PairedEndLibrary/spec.json
- types/KBaseFile.SingleEndLibrary/spec.json
- types/KBaseGenomeAnnotations.Assembly/spec.json
- types/KBaseGenomes.Genome/spec.json
- types/KBaseRNASeq.RNASeqAlignment/spec.json
This adds staging export options to large types.
> Add staging options

- types/KBaseFBA.FBAModel/spec.json
Already tested on CI and it's looking good
> Use new module for SBML exports

- types/KBaseFBA.FBAModel/spec.json
- types/KBaseGenomes.Genome/spec.json
using new SBML exportor on prod.
> dev -> master
